### ISSUE TITLE
Add Ctrl-C to copy text from chat history

### ISSUE THREAD

**Issue by grandoth** [JocysCom/VsAiCompanion#13]
Environment
Windows 11 22H2
Visual Studio 2022 (17.10.3)
VS AI Companion 1.11.25.0 (Extension)

When on the main tab of a Task (for AI - Chat), selecting text in the chat history and pressing Ctrl-C does not trigger Copy to Clipboard. Selecting Copy from the context menu does work however. Please consider adding this hotkey combo for ease of use.

Note: Ctrl-C on the Instructions, Prompts, and Task Search textboxes does trigger Copy to Clipboard.

**Comment by EJocys** [comment]
@grandoth Thanks for reporting the issue. Visual Studio blocks CTRL+C for the WebBrowser. Released a new version that monitors for CTRL+C key presses and triggers `Copy` in the WebBrowser.

2024-06-30 v1.12.6

- Fix: List not expanding.
- Fix: Improved support for Azure SQL Server Databases.
- Fix: Unable to stop message requests.
- Fix: Embedding search group filter not working correctly.
- Fix: Allow CTRL+C copy in web browser from Visual Studio extension.
- Update: SQL now uses native SQL script AI search instead of C# Assembly.
- Update: UI, Templates and AI Avatar updated.
- New: Create UI presets, like "Simple" or "Advanced".

https://github.com/JocysCom/VsAiCompanion/releases
